[package]
name = "unitycatalog-client"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "unitycatalog_client"
crate-type = ["cdylib"]

[dependencies]
unitycatalog-common = { path = "../../unitycatalog/common", features = [
  "python",
] }

pyo3 = "0.24.0"
